apiVersion: v2
name: egressgateway
home: "https://spidernet-io.github.io/agent"
# application or library
type: application
# no need to modify this version , CI will auto update it with /VERSION
version: "0.3.0-rc0"
# This field is informational, and has no impact on chart version calculations .
# Leaving it unquoted can lead to parsing issues in some cases
# no need to modify this version , CI will auto update it with /VERSION
appVersion: "0.3.0-rc0"
kubeVersion: ">= 1.16.0-0"
description: egressgateway
sources:
  - "https://github.com/spidernet-io/egressgateway"
keywords:
  - egressgateway
maintainers:
  - name: spidernet-io
    url: https://github.com/spidernet-io
