# make sure the pr is labeled as wanted, case: we could generate changelog by the pr label
name: PR Label Check

# Trigger the workflow on pull requests only
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

env:
  RELEASE_LABELS: "release/bug, release/feature, release/none, pr/robot_update"

jobs:
  check-label:
    name: Check release-note label set
    runs-on: ubuntu-latest
    steps:
      # must set one of required label, for release note generator
      - uses: mheap/github-action-required-labels@v2.1.0
        with:
          mode: exactly
          count: 1
          labels: ${{ env.RELEASE_LABELS }}
